/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Jan 11, 2005, 12:03:27 PM
 */

package calculator;

import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 *
 * @author Ahsan
 */
public class Main_Calculator extends javax.swing.JFrame {
    public static String p,idview,idcalculation,s1,s2,s3,s4,itmstate="Infix";
    public static int on=0,prenextview=0,prenextcalculation=0;
    public  static String cal1[]=new String[100];
    /** Creates new form NewJFrame */
    public Main_Calculator() {
        initComponents();
    }
    private class RadioBtn implements ItemListener{
            private String btnitm;
            public RadioBtn(String s){
                btnitm=s;
            }

        public void itemStateChanged(ItemEvent e) {
            itmstate=btnitm;

        }
        }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        inputTextField = new javax.swing.JTextField();
        outputTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        onOffToggleButton = new javax.swing.JToggleButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        pointButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        lnutton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        tenToThePowerButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        divitionButton = new javax.swing.JButton();
        sinButton = new javax.swing.JButton();
        InverseSinButton = new javax.swing.JButton();
        multiplicationButton = new javax.swing.JButton();
        tanButton = new javax.swing.JButton();
        inverseTanButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        inverseCosButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        piButton = new javax.swing.JButton();
        qubeRootButton = new javax.swing.JButton();
        factorialButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        nPrButton = new javax.swing.JButton();
        nCrButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        xToThePowerNButton = new javax.swing.JButton();
        SquareButton = new javax.swing.JButton();
        leftBrackesButton = new javax.swing.JButton();
        rightBrackesButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        calculatorMenu = new javax.swing.JMenu();
        infixRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        prefixRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        postfixRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        modeMenu = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        scientifiqRadioBtnMenu = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        exitMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuBtn = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        aboutMenuBtn = new javax.swing.JMenuItem();

        buttonGroup1.add(scientifiqRadioBtnMenu);

        buttonGroup2.add(postfixRadioButtonMenuItem);
        buttonGroup2.add(prefixRadioButtonMenuItem);
        buttonGroup2.add(infixRadioButtonMenuItem);
        infixRadioButtonMenuItem.addItemListener(new RadioBtn("infix"));
        prefixRadioButtonMenuItem.addItemListener(new RadioBtn("prefix"));
        postfixRadioButtonMenuItem.addItemListener(new RadioBtn("postfix"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clearButton.setText("Clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        delButton.setText("Del");
        delButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delButtonMouseClicked(evt);
            }
        });

        onOffToggleButton.setBackground(new java.awt.Color(243, 243, 243));
        onOffToggleButton.setText("On/Off");
        onOffToggleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onOffToggleButtonMouseClicked(evt);
            }
        });

        sevenButton.setText("7");
        sevenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenButtonMouseClicked(evt);
            }
        });

        eightButton.setText("8");
        eightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightButtonMouseClicked(evt);
            }
        });

        nineButton.setText("9");
        nineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineButtonMouseClicked(evt);
            }
        });

        fourButton.setText("4");
        fourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourButtonMouseClicked(evt);
            }
        });

        fiveButton.setText("5");
        fiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveButtonMouseClicked(evt);
            }
        });

        sixButton.setText("6");
        sixButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixButtonMouseClicked(evt);
            }
        });

        oneButton.setText("1");
        oneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneButtonMouseClicked(evt);
            }
        });

        twoButton.setText("2");
        twoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoButtonMouseClicked(evt);
            }
        });

        threeButton.setText("3");
        threeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeButtonMouseClicked(evt);
            }
        });

        zeroButton.setText("0");
        zeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroButtonMouseClicked(evt);
            }
        });

        pointButton.setText(".");
        pointButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pointButtonMouseClicked(evt);
            }
        });

        equalButton.setBackground(new java.awt.Color(231, 183, 188));
        equalButton.setForeground(new java.awt.Color(33, 17, 18));
        equalButton.setText("=");
        equalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equalButtonMouseClicked(evt);
            }
        });

        lnutton.setText("ln");
        lnutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnuttonMouseClicked(evt);
            }
        });

        eButton.setText("e");
        eButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eButtonMouseClicked(evt);
            }
        });

        tenToThePowerButton.setText("10^");
        tenToThePowerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenToThePowerButtonMouseClicked(evt);
            }
        });

        plusButton.setBackground(new java.awt.Color(231, 183, 188));
        plusButton.setText("+");
        plusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusButtonMouseClicked(evt);
            }
        });

        divitionButton.setBackground(new java.awt.Color(231, 183, 188));
        divitionButton.setText("/");
        divitionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divitionButtonMouseClicked(evt);
            }
        });

        sinButton.setText("sin");
        sinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinButtonMouseClicked(evt);
            }
        });

        InverseSinButton.setText("inv(sin)");
        InverseSinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InverseSinButtonMouseClicked(evt);
            }
        });

        multiplicationButton.setBackground(new java.awt.Color(231, 183, 188));
        multiplicationButton.setText("*");
        multiplicationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicationButtonMouseClicked(evt);
            }
        });

        tanButton.setText("tan");
        tanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanButtonMouseClicked(evt);
            }
        });

        inverseTanButton.setText("inv(tan)");
        inverseTanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inverseTanButtonMouseClicked(evt);
            }
        });

        logButton.setText("log");
        logButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logButtonMouseClicked(evt);
            }
        });

        minusButton.setBackground(new java.awt.Color(231, 183, 188));
        minusButton.setText("-");
        minusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusButtonMouseClicked(evt);
            }
        });

        inverseCosButton.setText("inv(cos)");
        inverseCosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inverseCosButtonMouseClicked(evt);
            }
        });

        cosButton.setText("cos");
        cosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cosButtonMouseClicked(evt);
            }
        });

        piButton.setBackground(new java.awt.Color(231, 183, 188));
        piButton.setText("pi");
        piButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piButtonMouseClicked(evt);
            }
        });

        qubeRootButton.setText("x^(1/3)");
        qubeRootButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qubeRootButtonMouseClicked(evt);
            }
        });

        factorialButton.setText("!");
        factorialButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                factorialButtonMouseClicked(evt);
            }
        });

        nextButton.setText(">");
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonMouseClicked(evt);
            }
        });

        nPrButton.setText("nPr");
        nPrButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nPrButtonMouseClicked(evt);
            }
        });

        nCrButton.setText("nCr");
        nCrButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nCrButtonMouseClicked(evt);
            }
        });

        previousButton.setText("<");
        previousButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousButtonMouseClicked(evt);
            }
        });

        xToThePowerNButton.setText("x^n");
        xToThePowerNButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xToThePowerNButtonMouseClicked(evt);
            }
        });

        SquareButton.setText("Root(");
        SquareButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SquareButtonMouseClicked(evt);
            }
        });

        leftBrackesButton.setText("(");
        leftBrackesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftBrackesButtonMouseClicked(evt);
            }
        });

        rightBrackesButton.setText(")");
        rightBrackesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightBrackesButtonMouseClicked(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(212, 212, 212));

        calculatorMenu.setText("Calculator");
        calculatorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorMenuActionPerformed(evt);
            }
        });

        infixRadioButtonMenuItem.setSelected(true);
        infixRadioButtonMenuItem.setText("Infix");
        infixRadioButtonMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infixRadioButtonMenuItemMouseClicked(evt);
            }
        });
        calculatorMenu.add(infixRadioButtonMenuItem);

        prefixRadioButtonMenuItem.setSelected(false);
        prefixRadioButtonMenuItem.setText("Prefix");
        prefixRadioButtonMenuItem.setDisplayedMnemonicIndex(1);
        calculatorMenu.add(prefixRadioButtonMenuItem);

        postfixRadioButtonMenuItem.setSelected(false);
        postfixRadioButtonMenuItem.setText("Postfix");
        calculatorMenu.add(postfixRadioButtonMenuItem);

        jMenuBar1.add(calculatorMenu);

        modeMenu.setText("Mode");
        modeMenu.add(jSeparator1);

        scientifiqRadioBtnMenu.setText("Scientifiq");
        modeMenu.add(scientifiqRadioBtnMenu);
        modeMenu.add(jSeparator2);

        exitMenu.setText("Exit");
        modeMenu.add(exitMenu);

        jMenuBar1.add(modeMenu);

        contentMenuBtn.setText("Content");
        helpMenu.add(contentMenuBtn);
        helpMenu.add(jSeparator3);

        aboutMenuBtn.setText("About");
        helpMenu.add(aboutMenuBtn);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(onOffToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(piButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inverseCosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(divitionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(InverseSinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inverseTanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tenToThePowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lnutton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(leftBrackesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rightBrackesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nCrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nPrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(xToThePowerNButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(factorialButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SquareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qubeRootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(inputTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(outputTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onOffToggleButton)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inverseCosButton)
                            .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(piButton)
                            .addComponent(cosButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sevenButton)
                                    .addComponent(eightButton)
                                    .addComponent(nineButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fourButton)
                                    .addComponent(fiveButton)
                                    .addComponent(sixButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(oneButton)
                                    .addComponent(twoButton)
                                    .addComponent(threeButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(zeroButton)
                                    .addComponent(pointButton)
                                    .addComponent(equalButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(divitionButton)
                                    .addComponent(sinButton)
                                    .addComponent(InverseSinButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(multiplicationButton)
                                    .addComponent(tanButton)
                                    .addComponent(inverseTanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(minusButton)
                                    .addComponent(logButton)
                                    .addComponent(tenToThePowerButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(plusButton)
                                    .addComponent(lnutton)
                                    .addComponent(eButton)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leftBrackesButton)
                            .addComponent(rightBrackesButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nCrButton)
                            .addComponent(nPrButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xToThePowerNButton)
                            .addComponent(factorialButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SquareButton)
                            .addComponent(previousButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qubeRootButton)
                            .addComponent(nextButton))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculatorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calculatorMenuActionPerformed
public String actionperformed(ActionEvent evt){
String masud=evt.getActionCommand();
return masud;
}
    private void sevenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenButtonMouseClicked
        if(on==0){
        }
    else{
        p="";
        s1="";
        s2="";
        s3="";
        s4="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("7");
        idcalculation="7";
        prenextview++;
        prenextcalculation++;
        
        }
        else
        {
        String s="7";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++;
         prenextcalculation++;
        }
    }//GEN-LAST:event_sevenButtonMouseClicked
}
        private void eightButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightButtonMouseClicked
    if(on==0){}
    else{
         p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("8");
        idcalculation="8";
       prenextview++; prenextcalculation++;
        }
        else
        {
        String s="8";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
         inputTextField.setText(idview);
        prenextview++; prenextcalculation++;
        }
        }
        }//GEN-LAST:event_eightButtonMouseClicked

        private void nineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineButtonMouseClicked
        if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("9");
        idcalculation="9";
        prenextview++; prenextcalculation++;
        }
        else
        {
        String s="9";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++; prenextcalculation++;
        }
            }
        }//GEN-LAST:event_nineButtonMouseClicked

        private void fourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourButtonMouseClicked
          if(on==0){}
          else{
            p="";
            idview=inputTextField.getText();
            if(p.equals(idview))

            {inputTextField.setText("4");
            idcalculation="4";
            prenextview++; prenextcalculation++;
            }
            else
            {
            String s="4";
             s1=idview.substring(0,prenextview);
            s2=idview.substring(prenextview,idview.length());
            s1=s1.concat(s);
            idview=s1.concat(s2);
            s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
            inputTextField.setText(idview);
            prenextview++; prenextcalculation++;
            }
            }
        }//GEN-LAST:event_fourButtonMouseClicked

        private void fiveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveButtonMouseClicked
        if(on==0){}
          else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("5");
        idcalculation="5";
        prenextview++; prenextcalculation++;
        }
        else
        {
        String s="5";
         s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
      s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++; prenextcalculation++;
            }
        }
        }//GEN-LAST:event_fiveButtonMouseClicked

        private void sixButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixButtonMouseClicked
        if(on==0){}
          else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("6");
        idcalculation="6";
        prenextview++; prenextcalculation++;
        }
        else
        {
        String s="6";
         s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++; prenextcalculation++;
        }
        }
        }//GEN-LAST:event_sixButtonMouseClicked

        private void oneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneButtonMouseClicked
        if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("1");
        idcalculation="1";
        prenextview++; prenextcalculation++;
        }
        else
        {
        String s="1";
         s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
       prenextview++; prenextcalculation++;
          }
           }
        }//GEN-LAST:event_oneButtonMouseClicked

        private void twoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoButtonMouseClicked
        if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("2");
        idcalculation="2";
        prenextview++; prenextcalculation++;
        }
        else
        {
        String s="2";
         s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
         inputTextField.setText(idview);
        prenextview++; prenextcalculation++;
        }
      }
        }//GEN-LAST:event_twoButtonMouseClicked

        private void threeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeButtonMouseClicked
         if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("3");
        idcalculation="3";
        prenextview++; prenextcalculation++;
        }
        else
        {
        String s="3";
         s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++; prenextcalculation++;
        }
        }
        }//GEN-LAST:event_threeButtonMouseClicked

        private void zeroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroButtonMouseClicked

         if(on==0){}
        else{p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("0");
        idcalculation="0";
        prenextview++; prenextcalculation++;
        }
        else
        {
        String s="0";
         s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++; prenextcalculation++;
        }
        }
        }//GEN-LAST:event_zeroButtonMouseClicked

        private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
         inputTextField.setText("");
         idcalculation="";
         prenextview=0;
          prenextcalculation=0;
          outputTextField.setText("");
        }//GEN-LAST:event_clearButtonMouseClicked

        private void pointButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pointButtonMouseClicked

        if(on==0){}
        else{p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText(".");
        idcalculation=".";
        prenextview++; prenextcalculation++;
        }
        else
        {
        String s=".";
         s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
          inputTextField.setText(idview);
        prenextview++; prenextcalculation++;
        }
        }
        }//GEN-LAST:event_pointButtonMouseClicked

        private void delButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delButtonMouseClicked

        if(on==0){}
        else{p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {
        }
        else
        {
        s1=idview.substring(0, idview.length()-1);
       if(idcalculation.charAt(prenextcalculation-1)=='+')
       {
        s2=idcalculation.substring(0,idcalculation.length()-2);
        prenextcalculation-=2;
            }
            else if (idcalculation.charAt(prenextcalculation - 1) == '-')
       {
           s2 = idcalculation.substring(0, idcalculation.length() - 2);
           prenextcalculation-=2;}
                else if(idcalculation.charAt(prenextcalculation - 1) == '*')
       {
                    s2=idcalculation.substring(0,idcalculation.length()-2);
                    prenextcalculation-=2;}
                    else if(idcalculation.charAt(prenextcalculation - 1) == '/')
       {
                        s2=idcalculation.substring(0,idcalculation.length()-2);
                        prenextcalculation-=2;}
       else
       {
           s2=idcalculation.substring(0,idcalculation.length()-1);
           prenextcalculation--;
       }
        idview=s1;
        idcalculation=s2;
          inputTextField.setText(idview);
        prenextview--;
      
           
         }
         }
        }//GEN-LAST:event_delButtonMouseClicked

        private void piButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piButtonMouseClicked
        if(on==0){}
        else{ p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("pi");
        idcalculation="pi";
        prenextview+=2;prenextcalculation+=2;
        }
        else
        {
        String s="pi";
         s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
       inputTextField.setText(idview);
        prenextview+=2;prenextcalculation+=2;
          }
          }
        }//GEN-LAST:event_piButtonMouseClicked

        private void divitionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divitionButtonMouseClicked

            if(on==0){}
        else{p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("/");
        idcalculation="/,";
        prenextview++;prenextcalculation+=2;
        }
        else
        {
        String s="/";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
         s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        if(idcalculation.substring(idcalculation.length()-1).equals(","))
        {
            s = "/,";
            prenextcalculation+=2;
        }
        else
        {
            s=",/,";
            prenextcalculation+=3;
        }


        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++;
        }
        }
        }//GEN-LAST:event_divitionButtonMouseClicked

        private void multiplicationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicationButtonMouseClicked

             if(on==0){}
        else{p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("*");
        idcalculation="*,";
        prenextview++;prenextcalculation+=2;
        }
        else
        {
        String s="*";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
         s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        if(idcalculation.substring(idcalculation.length()-1).equals(","))
        {
            s = "*,";
            prenextcalculation+=2;
        }
        else
        {
            s=",*,";
            prenextcalculation+=3;
        }

       
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++;
        }
        }
        }//GEN-LAST:event_multiplicationButtonMouseClicked

        private void minusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusButtonMouseClicked

             if(on==0){}
        else{p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("-");
        idcalculation="-,";
        prenextview++;prenextcalculation+=2;
        }
        else
        {
       String s="-";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
         s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        if(idcalculation.substring(idcalculation.length()-1).equals(","))
        {
            s = "-,";
            prenextcalculation+=2;
        }
        else
        {
            s=",-,";
            prenextcalculation+=3;
        }

     
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++;
                 }
        }
        }//GEN-LAST:event_minusButtonMouseClicked

        private void plusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusButtonMouseClicked

             if(on==0){}
        else{p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("+");
        idcalculation="+,";
        prenextview++;prenextcalculation+=2;
        }
        else
        {
        String s="+";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        if(idcalculation.substring(idcalculation.length()-1).equals(","))
        {
            s = "+,";
            prenextcalculation+=2;
        }
        else
        {
            s=",+,";
            prenextcalculation+=3;
        }

        
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
          inputTextField.setText(idview);
        prenextview++;
                 }
        }
        }//GEN-LAST:event_plusButtonMouseClicked

        private void cosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cosButtonMouseClicked
             if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("cos");
        idcalculation="cos";
        prenextview+=3;prenextcalculation+=3;
        }
        else
        {
        String s="cos";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
         inputTextField.setText(idview);
        prenextview+=3;prenextcalculation+=3;
        }
        }//GEN-LAST:event_cosButtonMouseClicked
    }
        private void sinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinButtonMouseClicked
             if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("sin");
        idcalculation="sin";
        prenextview+=3;prenextcalculation+=3;
        }
        else
        {
        String s="sin";
       s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
         inputTextField.setText(idview);
        prenextview+=3;prenextcalculation+=3;
        }
        }// TODO add your handling code here:
        }//GEN-LAST:event_sinButtonMouseClicked

        private void tanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanButtonMouseClicked
             if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("tan");
        idcalculation="tan";
        prenextview+=3;prenextcalculation+=3;
        }
        else
        {
        String s="tan";
     s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
         inputTextField.setText(idview);
        prenextview+=3;prenextcalculation+=3;// TODO add your handling code here:
                 }
        }   // TODO add your handling code here:
        }//GEN-LAST:event_tanButtonMouseClicked

        private void logButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButtonMouseClicked
      if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("log");
        idcalculation="log";
        prenextview+=3;prenextcalculation+=3;
        }
        else
        {
        String s="log";
       s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview+=3;prenextcalculation+=3;
          }
        }            // TODO add your handling code here:
        }//GEN-LAST:event_logButtonMouseClicked

        private void lnuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnuttonMouseClicked
      if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("ln");
        idcalculation="ln";
        prenextview+=2;prenextcalculation+=2;
        }
        else
        {
        String s="ln";
     s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
         inputTextField.setText(idview);
        prenextview+=2;prenextcalculation+=2;
        }
        }            // TODO add your handling code here:
        }//GEN-LAST:event_lnuttonMouseClicked

        private void inverseCosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inverseCosButtonMouseClicked
      if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("invcos");
        idcalculation="invcos";
        prenextview+=6;
        prenextcalculation+=6;
        }
        else
        {
        String s="invcos";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview+=6;prenextcalculation+=6;
          }
        }            // TODO add your handling code here:
        }//GEN-LAST:event_inverseCosButtonMouseClicked

        private void InverseSinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InverseSinButtonMouseClicked
        if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("invsin");
        idcalculation="invsin";
        prenextview+=6;
        prenextcalculation+=6;
        }
        else
        {
        String s="invsin";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
       inputTextField.setText(idview);
        prenextview+=6;prenextcalculation+=6;
        }  
            }// TODO add your handling code here:
        }//GEN-LAST:event_InverseSinButtonMouseClicked

        private void inverseTanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inverseTanButtonMouseClicked
         if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("invtan");
        idcalculation="invtan";
        prenextcalculation+=6;prenextview+=6;
        }
        else
        {
        String s="invtan";
         s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
         inputTextField.setText(idview);
        prenextview+=6;prenextcalculation+=6;// TODO add your handling code here:
             }
        }            // TODO add your handling code here:
        }//GEN-LAST:event_inverseTanButtonMouseClicked

        private void tenToThePowerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenToThePowerButtonMouseClicked
     if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("10^");
        idcalculation="10^";
        prenextview+=3;prenextcalculation+=3;
        }
        else
        {
        String s="10^";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
         inputTextField.setText(idview);
        prenextview+=3;prenextcalculation+=3;// TODO add your handling code here:
         }
        }            // TODO add your handling code here:
        }//GEN-LAST:event_tenToThePowerButtonMouseClicked

        private void eButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eButtonMouseClicked
     if(on==0){}
            else{
                p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("e");
        idcalculation="e";
        prenextview++;prenextcalculation++;
        }
        else
        {
        String s="e";
       s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
         inputTextField.setText(idview);
        prenextview++;prenextcalculation++;// TODO add your handling code here:
         }
        }            // TODO add your handling code here:
        }//GEN-LAST:event_eButtonMouseClicked

        private void leftBrackesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftBrackesButtonMouseClicked
             if(on==0){}
        else{p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("(");
        idcalculation="(,";
        prenextview++;prenextcalculation+=2;
        }
        else
        {
        String s="(";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());

        if(idcalculation.substring(idcalculation.length()-1).equals(","))
        {
            s = "(,";
            prenextcalculation+=2;
        }
        else
        {
            s=",(,";
            prenextcalculation+=3;
        }

        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++;  }
        }        // TODO add your handling code here:
        }//GEN-LAST:event_leftBrackesButtonMouseClicked

        private void nCrButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nCrButtonMouseClicked
         if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("C");
        idcalculation="C";
        prenextview++;prenextcalculation++;
        }
        else
        {
        String s="C";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++;prenextcalculation++;// TODO add your handling code here:
             }
        }                    // TODO add your handling code here:
        }//GEN-LAST:event_nCrButtonMouseClicked

        private void xToThePowerNButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xToThePowerNButtonMouseClicked
     if(on==0){}
            else{
                p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("^");
        idcalculation="^";
        prenextview++;prenextcalculation++;
        }
        else
        {
        String s="^";
       s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
         inputTextField.setText(idview);
        prenextview++;prenextcalculation++;// TODO add your handling code here:
         }
        }                    // TODO add your handling code here:
        }//GEN-LAST:event_xToThePowerNButtonMouseClicked

        private void rightBrackesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightBrackesButtonMouseClicked

             if(on==0){}
        else{p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText(")");
        idcalculation="),";
        prenextview++;prenextcalculation+=2;
        }
        else
        {
        String s=")";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());

        if(idcalculation.substring(idcalculation.length()-1).equals(","))
        {
            s = "),";
            prenextcalculation+=2;
        }
        else
        {
            s=",),";
            prenextcalculation+=3;
        }

        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++;
             }

        }                    // TODO add your handling code here:
        }//GEN-LAST:event_rightBrackesButtonMouseClicked

        private void nPrButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nPrButtonMouseClicked
     if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("P");
        idcalculation="P";
        prenextview++;prenextcalculation++;
        }
        else
        {
        String s="P";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
       inputTextField.setText(idview);
        prenextview++;prenextcalculation++;// TODO add your handling code here:
         }
        }                    // TODO add your handling code here:
        }//GEN-LAST:event_nPrButtonMouseClicked

        private void SquareButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SquareButtonMouseClicked
         if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("Root");
        idcalculation="Root";
        prenextview+=4;prenextcalculation+=4;
        }
        else
        {
        String s="Root";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview+=4;prenextcalculation+=4;// TODO add your handling code here:
             }
        }                    // TODO add your handling code here:
        }//GEN-LAST:event_SquareButtonMouseClicked

        private void qubeRootButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qubeRootButtonMouseClicked
         if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("qube");
        idcalculation="qube";
        prenextview+=4;prenextcalculation+=4;
        }
        else
        {
        String s="qube";
        s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
        s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
       inputTextField.setText(idview);
        prenextview+=4;prenextcalculation+=4;// TODO add your handling code here:
             }
        }                    // TODO add your handling code here:
        }//GEN-LAST:event_qubeRootButtonMouseClicked

        private void factorialButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_factorialButtonMouseClicked
     if(on==0){}
        else{
            p="";
        idview=inputTextField.getText();
        if(p.equals(idview))

        {inputTextField.setText("!");
        idcalculation="!";
        prenextview++;prenextcalculation+=1;
        }
        else
        {
        String s="!";
       s1=idview.substring(0,prenextview);
        s2=idview.substring(prenextview,idview.length());
        s1=s1.concat(s);
        idview=s1.concat(s2);
       s3=idcalculation.substring(0,prenextcalculation);
        s4=idcalculation.substring(prenextcalculation,idcalculation.length());
        s3=s3.concat(s);
        idcalculation=s3.concat(s4);
        inputTextField.setText(idview);
        prenextview++;prenextcalculation+=1;// TODO add your handling code here:
         }
        }                    // TODO add your handling code here:
        }//GEN-LAST:event_factorialButtonMouseClicked

        private void onOffToggleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onOffToggleButtonMouseClicked
           if(on==0)
           {
           on=1;
           }
 else
     if(on==1){
     on=0;
     inputTextField.setText("");
     idcalculation="";
     }// TODO add your handling code here:
        }//GEN-LAST:event_onOffToggleButtonMouseClicked

        private void previousButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButtonMouseClicked
            
            prenextview--;
            if(idcalculation.charAt(prenextcalculation-1)=='+')
       {

        prenextcalculation-=2;
            }
            else if (idcalculation.charAt(prenextcalculation - 1) == '-')
       {

           prenextcalculation-=2;}
                else if(idcalculation.charAt(prenextcalculation - 1) == '*')
       {

                    prenextcalculation-=2;}
                    else if(idcalculation.charAt(prenextcalculation - 1) == '/')
       {

                        prenextcalculation-=2;}
       else
       {
           s2=idcalculation.substring(0,idcalculation.length()-1);
           prenextcalculation--;
       }// TODO add your handling code here:
        }//GEN-LAST:event_previousButtonMouseClicked

        private void nextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseClicked
           idview=inputTextField.getText();
           if(prenextview<idview.length())
           {
            prenextview++;
             if(idcalculation.charAt(prenextcalculation-1)=='+')
       {
       
        prenextcalculation+=2;
            }
            else if (idcalculation.charAt(prenextcalculation - 1) == '-')
       {
          
           prenextcalculation+=2;}
                else if(idcalculation.charAt(prenextcalculation - 1) == '*')
       {
                   
                    prenextcalculation+=2;}
                    else if(idcalculation.charAt(prenextcalculation - 1) == '/')
       {
                       
                        prenextcalculation+=2;}
       else
       {
           s2=idcalculation.substring(0,idcalculation.length()-1);
           prenextcalculation++;
       }

            }// TODO add your handling code here:
        }//GEN-LAST:event_nextButtonMouseClicked

        private void equalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalButtonMouseClicked
        
         outputTextField.setText("");
        
        
         idview=inputTextField.getText();

        if(itmstate == null ? "postfix" == null : itmstate.equals("postfix")){
         String res=MyCalculator.Postfixcal(idview);
         String s="";
         for(int i=0;i<500;i++)
             s+=" ";
         s+=res;
         outputTextField.setText(s);
            }
         if(itmstate == null ? "prefix" == null : itmstate.equals("prefix")){
         String res=MyCalculator.Prefixcal(idview);
         String s="";
         for(int i=0;i<500;i++)
             s+=" ";
         s+=res;
         outputTextField.setText(s);
            }
           if(itmstate == null ? "infix" == null : itmstate.equals("infix")){
         String idcal[]=idcalculation.split(",");
             String res=polish.Infixcal(MathFuncTest.test(idcal));
         String s="";
         for(int i=0;i<500;i++)
            s+=" ";
         s+=res;
       // for(int i=0;i<idcal.length;i++)
         //  s+=idcal[i];
         outputTextField.setText(s);
            }
        
       
         
        }//GEN-LAST:event_equalButtonMouseClicked

        private void prefixRadioButtonMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prefixRadioButtonMenuItemMouseClicked
            //buttonGroup2.clearSelection();
            //prefixRadioButtonMenuItem.setSelected(true);// TODO add your handling code here:
        }//GEN-LAST:event_prefixRadioButtonMenuItemMouseClicked

        private void infixRadioButtonMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infixRadioButtonMenuItemMouseClicked
            // TODO add your handling code here:
        }//GEN-LAST:event_infixRadioButtonMenuItemMouseClicked
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InverseSinButton;
    private javax.swing.JButton SquareButton;
    private javax.swing.JMenuItem aboutMenuBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JMenu calculatorMenu;
    private javax.swing.JButton clearButton;
    private javax.swing.JMenuItem contentMenuBtn;
    private javax.swing.JButton cosButton;
    private javax.swing.JButton delButton;
    private javax.swing.JButton divitionButton;
    private javax.swing.JButton eButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JButton factorialButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JRadioButtonMenuItem infixRadioButtonMenuItem;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JButton inverseCosButton;
    private javax.swing.JButton inverseTanButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JButton leftBrackesButton;
    private javax.swing.JButton lnutton;
    private javax.swing.JButton logButton;
    private javax.swing.JButton minusButton;
    private javax.swing.JMenu modeMenu;
    private javax.swing.JButton multiplicationButton;
    private javax.swing.JButton nCrButton;
    private javax.swing.JButton nPrButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JToggleButton onOffToggleButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JTextField outputTextField;
    private javax.swing.JButton piButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton pointButton;
    private javax.swing.JRadioButtonMenuItem postfixRadioButtonMenuItem;
    private javax.swing.JRadioButtonMenuItem prefixRadioButtonMenuItem;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton qubeRootButton;
    private javax.swing.JButton rightBrackesButton;
    private javax.swing.JRadioButtonMenuItem scientifiqRadioBtnMenu;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sinButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton tanButton;
    private javax.swing.JButton tenToThePowerButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton xToThePowerNButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables

}
